### ISSUE TITLE
Tutorial hints

### ISSUE THREAD

**Issue by ericmjl** [chdoig/scipy2015-blaze-bokeh#2]
Hi Christine!

Thank you for the time and effort you put into preparing the tutorial! 

I had a suggestion for modifying the tutorial material post-tutorial session, hopefully this doesn't take up too much time, and hopefully you might consider it.

Would you consider putting URLs to the pages where we could grab hints/learn by examples? A few examples:
1. Notebook (NB) 1.2: prior to "Axis Format", a link to a page that shows an example of formatting axis dates. 
2. NB 1.2: a link to the `figure()` source code, so that we can inspect the `figure` attributes.

There are others too that would have helped us during the coding challenges.

Hope you have a great rest of the conference!

**Comment by rhiever** [comment]
I support this suggestion. Some Google-fu will take users to the right docs, but I don't think many people thought to look up the docs.

**Comment by chdoig** [comment]
Hi Eric,

I had some of the relevant docs in the slides, before each exercise, but I should probably link them in the notebooks too and add any missing ones, so that people don't have to switch between the notebooks and the slides.

Thanks!

**Comment by ericmjl** [comment]
Hi Christine,

Got it! Thanks again for all the effort you put into preparing the tutorial material! :)
