### ISSUE TITLE
Tutorial comments

### ISSUE THREAD

**Issue by msarahan** [chdoig/scipy2015-blaze-bokeh#4]
Hi, less an issue here and more commentary.

I very much enjoyed your presentation.  I found the flow from simple plots to more extensive, integrated dashboards was excellent.  I was tripped up by some small things, and thought the following might improve the whole for any future tutorials:
- Avoid file reading with NetCDF, or provide the code to do the reading directly.  The tutorial is about Bokeh, and the focus should not stray from it.
- Build/aggregate reusable code blocks more directly.  Your cells with comments in the notebook are very helpful for breaking the problem up into parts, but it was frustrating to say "OK, now copy-paste your earlier code into this new area (but go fetch your mess of code from lots of cells earlier.)"  It was disorienting at best.  I don't know a good compromise between keeping the nice in-line display and problem break-up of the IPython Notebook, while also keeping a more file-based view that is easy to change and work into cohesive code blocks.  So, I'm whining without a suggestion of a solution (sorry), but wanted to mention this as something that slowed down my learning.
- Show the complete example (the animation from elsewhere) at the very beginning, and use that as motivation for the entire day's activities.  I had a much greater appreciation for the different parts of the tutorial once I realized how you were tying them together.

Thanks again for your hard work on this tutorial.

**Comment by chdoig** [comment]
Hi, 

First of all, thanks for taking the time to write some feedback. I really appreciate it. Some thoughts on your issues:
- You're right. I had same thoughts when preparing the tutorial. I had some doubts of what to provide and what not to. I feel too much guidance can have counterproductive effects. But I believe that for that particular case, it's justified.
- I've been thinking about that too and I don't have a good solution for that either. I wanted a full narrative of building an actual app in incremental steps using ipython notebooks. For that, there is no really optimal solution, sometimes you need to copy paste from the previous notebooks.
- I did. I did show the animation in the introduction section: http://chdoig.github.io/scipy2015-blaze-bokeh/#/1/5. I showed the video in that slide. Were you late to the session? That would explain it.

**Comment by msarahan** [comment]
RE # 3: I was late.  I blame it on Thai How are You.  Poor lunch choice.  Sorry, and glad you have the animation in your intro!
